before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libfftw3-dev
language: ruby
rvm:
  - "1.8.7"
  - "1.9.3"
  - "2.0.0"
  - ree
  - rbx-2.1.1
  - rbx-2.2.0
  - rbx-2.2.1
allow_failures:
  rvm:
    - ruby-head
    - rbx-2.2.0
    - rbx-2.2.1